version: '3.7'
services:
  game_server:
    build:
      context: .
      dockerfile: Dockerfile.game_server
    container_name: game_server
    ports:
      - "7777:7777"

  nginx_proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - game_server
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '512M'