services:
  dedicated_server:
    build:
      context: .
      dockerfile: Dockerfile.dedicated
    container_name: dedicated_server
    ports:
      - "7777:7777"
    networks:
      - game_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '512M'

  nginx_server:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    networks:
      - game_network

networks:
  game_network:
    driver: bridge
