FROM nginx:latest

# 複製 WebGL 構建文件到 Nginx 容器
COPY ./Builds/WebGL/ /usr/share/nginx/html

# 複製 Nginx 配置文件
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# 複製 SSL 證書
COPY ./nginx/certs/ /etc/nginx/certs/

# Expose ports 80 and 443 for HTTP and HTTPS
EXPOSE 80 443

# Start Nginx with configuration test at runtime
CMD ["nginx", "-g", "daemon off;"]