version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: ayo-game-dev-resource/old-docker-runner
    steps:
      - run: echo "Hi I'm on Runners!"