version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner-test

jobs:
  runner-test:
    machine: true
    resource_class: ayo-game-dev-resource/container-runner
    steps:
      - run:
          name: print log
          command: echo "Hello, CircleCI!"
